spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_tracking_rra
spring.datasource.username=postgres
spring.datasource.password=yezu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=Zm9vYmFyYmF6cXV4cnl3ZXJ0eW9pa2xqd2VydHlkZmRmaWprbGprbGpkZmtsamtsZGZsa2pzbGptc2xrbW5vaXF3ZXJ0eQ==
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Logging
logging.level.org.springframework=INFO
logging.level.com.rra.vehicletracking=DEBUG

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
